config/routes.rb
Rails.application.routes.draw do
  # routes only accessible to users
  resources :billings
  resources :bookings
  get "cart", to: "cart#show"
  post "cart/add"
  post "cart/remove"
  get 'cart/show'
  
  # routes only accessible to admin
  authenticated :user, ->(user) { user.admin? } do
    get "dashboard", to: "dashboard#index"
    get "dashboard/bookings"
    get "dashboard/users"
    get "dashboard/services"
    get "dashboard/billings"
    get "dashboard/payments"
    get "dashboard/categories"
    get "dashboard/receipts"
    resources :categories
    resources :services
    resources :payments
  end

  devise_for :users
  root "bookings#index"

  # errors route 
  match "/404", to: "errors#not_found", via: :all
  match "/505", to: "errors#internal_server_error", via: :all

  # graphql
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :billing

  validates :street, :barangay, :city, :zipcode, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  has_many :bookings
  
  has_one :address, dependent: :destroy, inverse_of: :billing
  accepts_nested_attributes_for :address
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :service
  belongs_to :payment
  belongs_to :billing
  has_many :receipts, dependent: :destroy

  validates :user, presence: true
  validates :service, presence: true
  validates :payment, presence: true

  enum status: { pending: 0, served: 1, cancelled: 2 }
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items
  has_many :services, through: :cart_items

  def total 
    cart_items.to_a.sum { |cart_item| cart_item.total }
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :service
  belongs_to :cart

  def total
    service.price * slot
  end
end

app/models/category.rb
class Category < ApplicationRecord
  include ValidationConcern
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :services

  default_scope -> { order(updated_at: :desc) }
end

app/models/payment.rb
class Payment < ApplicationRecord
  validates :name, presence: true
  
  has_many :bookings
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :user
  # belongs_to :billing
  belongs_to :booking
end

app/models/service.rb
class Service < ApplicationRecord
  include ValidationConcern
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :user
  belongs_to :category
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :bookings

  validates :price, presence: true
  validates :available_date, presence: true, comparison: { greater_than: Time.zone.now, message: "must be set in the future or later." }
  validates :available_slots, presence: true
  validates :category_id, presence: true
  
  default_scope -> { order(updated_at: :desc) }
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :service
end

app/models/user.rb
class User < ApplicationRecord
  include UserConcern

  has_many :services, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :billings, dependent: :destroy
  has_many :receipts, dependent: :destroy
  has_one :cart, dependent: :destroy
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user

  def index
    @bookings = Booking.all
    @users = User.all
    @services = Service.all
    @billings = Billing.all
    @payments = Payment.all
    @categories = Category.all
    @receipts = Receipt.all
  end

  def bookings
    @bookings = Booking.all.includes(:payment, :user, service: [image_attachment: :blob])
    @most_booked_services = Service.all.includes(:category, :rich_text_description, image_attachment: :blob)
                                        .joins(:bookings)
                                        .group('services.id')
                                        .order('COUNT(bookings.id) DESC')
                                        .limit(1) # Limit the result to 3 records
  end

  def users
    @users = User.all
  end

  def services
    @services = Service.all.includes(:category, :rich_text_description, image_attachment: :blob)
  end

  def billings
    @billings = Billing.all.includes(:user)
  end

  def payments 
    @payments = Payment.all
  end

  def categories
    @categories = Category.all.includes(:rich_text_description, image_attachment: :blob)
  end

  def receipts
    @receipts = Receipt.all.includes(:user, booking: [:service, :payment])
  end
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/dashboard/_booking.html.erb
<%= content_tag :tr, id: dom_id(booking), class: dom_class(booking) do %>
  <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= booking.id %></td>
  <td class="border border-slate-300 dark:border-slate-700 p-4 text-sky-800 underline font-bold">
    <%= form_with(model: booking, method: :patch) do |form| %>
      <%= form.select :status, options_for_select(Booking.statuses.map { |key, value| [key.capitalize, key] }, 
      form.object.status), {}, { class: input_class, onchange: "this.form.submit()" }%>
    <% end %>
  </td>
  <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= booking.service.name %></td>
  <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800">₱<%= booking.service.price %></td>
  <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= image_tag booking.service.image, class: "w-12 h-12" %></td>
  <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= booking.service.available_date.strftime("%B %d, %Y") %></td>
  <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= booking.booked_time.strftime("%H:%M %p") %></td>
  <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= booking.slot%> slot(s)</td>
  <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= booking.payment.name%></td>
  <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= booking.user.name%></td>
  <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= time_ago_in_words(booking.created_at) %> ago</td>
  <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800">
    <%= link_to "Delete", booking, data: { turbo_method: :delete }, class: "bg-rose-500 hover:bg-rose-600 text-white rounded-md px-4 py-2 mt-2" %>
  </td>
<% end %>

app/views/dashboard/billings.html.erb
<% provide(:title, "Dashboard-Billings")%>
<div class="flex items-center justify-between pb-6 border-b">
  <h1 class="text-5xl font-bold text-gray-700">Billing Information's Dashboard</h1>
</div>

<table class="table-auto border-collapse border-slate-400 w-full">
<thead class="bg-slate-50 dark:bg-slate-700">
  <tr>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">id</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Name</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Email</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Mobile Number</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Complete Address</th>      
  </tr>
</thead>

<tbody>
  <% @billings.each do |billing| %>
    <%= content_tag :tr, id: dom_id(billing), class: dom_class(billing) do %>
      <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= billing.id %></td>
      <td class="border border-slate-300 dark:border-slate-700 p-4 text-sky-800 underline font-bold"><%= billing.user.name %></td>
      <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= billing.user.email %></td>
      <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= billing.user.mobile %></td>
      <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= billing.complete_address %></td>
    <% end %>
  <% end %>
</tbody>
</table>

app/views/dashboard/bookings.html.erb
<% provide(:title, "Dashboard-Bookings")%>
<div class="flex items-center justify-between pb-6 border-b">
  <h1 class="text-5xl font-bold text-gray-700">Booking's Dashboard</h1>
  <div>
  <h1 class="text-xl font-semibold text-gray-900">Most Booked Services</h1>
  <% if @most_booked_services.present? %>
    <% @most_booked_services.each do |service| %>
      <p>Service Name: <strong class="uppercase"><%= service.name %></strong></p>
      <p>Booking Count: <strong><%= service.bookings.count %></strong> </p>
    <% end %>
  <% else %>
    <p>No services found.</p>
  <% end %>
</div>
</div>

<div class="py-10 grid grid-cols-3 gap-6">
<%= link_to "#", class:"p-6 border shadow-xl rounded-xl block hover:shadow-lg transition ease-in duration-300 relative overflow-hidden" do %>
  <div class="h-1 w-full absolute top-0 left-0 right-0" style="background-color: #87CEEB">
  </div>
  <h3 class="font-medium text-2xl"><%= @bookings.pending.count %> pending</h3>
  <p class="text-gray-500">total number of bookings currently pending</p>
<% end %>

<%= link_to "#", class:"p-6 border shadow-xl rounded-xl block hover:shadow-lg transition ease-in duration-300 relative overflow-hidden" do %>
  <div class="h-1 w-full absolute top-0 left-0 right-0" style="background-color: #A3C1AD">
  </div>
  <h3 class="font-medium text-2xl"><%= @bookings.served.count %> served</h3>
  <p class="text-gray-500">total number of bookings currently served</p>
<% end %>

<%= link_to "#", class:"p-6 border shadow-xl rounded-xl block hover:shadow-lg transition ease-in duration-300 relative overflow-hidden" do %>
  <div class="h-1 w-full absolute top-0 left-0 right-0" style="background-color: #FFBF00">
  </div>
  <h3 class="font-medium text-2xl"><%= @bookings.cancelled.count %> cancelled</h3>
  <p class="text-gray-500">total number of bookings currently cancelled</p>
<% end %>
</div>


<% if @bookings.pending.any? %>
<h3 class="font-bold text-2xl mb-6 mt-10 pt-10 ">Pending Bookings</h3>
<table class="table-auto border-collapse border-slate-400 w-full">
<thead class="bg-slate-50 dark:bg-slate-700">
  <tr>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">id</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Status</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Name</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Price</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Service Image</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Booked Date</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Booked Time</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Booked slot(s)</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Payment method</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Booked by</th> 
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Booked last</th>   
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Action</th>         
  </tr>
</thead>

<tbody>
  <% @bookings.pending.each do |booking| %>
    <%= render "booking", booking: booking %>
  <% end %>
</tbody>
</table>
<% end%>

<% if @bookings.served.any? %>
<h3 class="font-bold text-2xl mb-6 mt-10 pt-10 ">Served Bookings</h3>
<table class="table-auto border-collapse border-slate-400 w-full">
<thead class="bg-slate-50 dark:bg-slate-700">
  <tr>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">id</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Status</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Name</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Price</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Service Image</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Booked Date</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Booked Time</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Booked slot(s)</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Payment method</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Booked by</th> 
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Booked last</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Action</th>        
  </tr>
</thead>

<tbody>
  <% @bookings.served.each do |booking| %>
    <%= render "booking", booking: booking %>
  <% end %>
</tbody>
</table>
<% end %>

<% if @bookings.cancelled.any? %>
<h3 class="font-bold text-2xl mb-6 mt-10 pt-10 ">Cancelled Bookings</h3>
<table class="table-auto border-collapse border-slate-400 w-full mb-24">
<thead class="bg-slate-50 dark:bg-slate-700">
  <tr>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">id</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Status</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Name</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Price</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Service Image</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Booked Date</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Booked Time</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Booked slot(s)</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Payment method</th>
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Booked by</th> 
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Booked last</th>  
    <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Action</th>      
  </tr>
</thead>

<tbody>
  <% @bookings.cancelled.each do |booking| %>
    <%= render "booking", booking: booking %>
  <% end %>
</tbody>
</table>
<% end %>

app/views/dashboard/categories.html.erb
<% provide(:title, "Dashboard-Categories")%>
<div class="flex items-center justify-between pb-6 border-b mb-6">
  <h1 class="text-5xl font-bold text-gray-700">Categories Dashboard</h1>
   <%= link_to "Add Category", new_category_path, class: button_class(theme: "primary")%>
</div>

<table class="table-auto border-collapse border-slate-400 w-full">
  <thead class="bg-slate-50 dark:bg-slate-700">
    <tr>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">id</th>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Name</th>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">description</th>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Image</th>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Action</th>         
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <%= content_tag :tr, id: dom_id(category), class: dom_class(category) do %>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= category.id %></td>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-sky-800 underline font-bold"><%= link_to category.name, category_path(category) %></td>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= category.description.to_plain_text %></td>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= image_tag category.image, class:"w-24" %></td>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800">
          <%= link_to "edit", edit_category_path(category), class: button_class(theme: "primary") if current_user.admin? %>
          <%= link_to "delete", category, data: { turbo_method: :delete}, class: button_class(theme: "dark") if current_user.admin? %>
        </td>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/dashboard/index.html.erb
<% provide(:title, "Dashboard")%>
<div class="flex items-center justify-between pb-6 border-b">
  <h1 class="text-5xl font-bold text-gray-700">Dashboard</h1>
</div>

<div class="py-10 grid grid-cols-3 gap-6">
  <%= link_to dashboard_bookings_path, class:"p-6 border shadow-xl rounded-xl block hover:shadow-lg transition ease-in duration-300 relative overflow-hidden" do %>
    <div class="h-1 w-full absolute top-0 left-0 right-0" style="background-color: #87CEEB">
    </div>
    <h3 class="font-medium text-2xl"><%= @bookings.count %> bookings</h3>
    <p class="text-gray-500">View dashboard page for bookings</p>
  <% end %>

  <%= link_to dashboard_services_path, class:"p-6 border shadow-xl rounded-xl block hover:shadow-lg transition ease-in duration-300 relative overflow-hidden" do %>
    <div class="h-1 w-full absolute top-0 left-0 right-0" style="background-color: #A3C1AD">
    </div>
    <h3 class="font-medium text-2xl"><%= @services.count %> services</h3>
    <p class="text-gray-500">View dashboard page for services</p>
  <% end %>

  <%= link_to dashboard_users_path, class:"p-6 border shadow-xl rounded-xl block hover:shadow-lg transition ease-in duration-300 relative overflow-hidden" do %>
    <div class="h-1 w-full absolute top-0 left-0 right-0" style="background-color: #FFBF00">
    </div>
    <h3 class="font-medium text-2xl"><%= @users.count %> users</h3>
    <p class="text-gray-500">View dashboard page for users</p>
  <% end %>

  <%= link_to dashboard_payments_path, class:"p-6 border shadow-xl rounded-xl block hover:shadow-lg transition ease-in duration-300 relative overflow-hidden" do %>
    <div class="h-1 w-full absolute top-0 left-0 right-0" style="background-color: #87CEEB">
    </div>
    <h3 class="font-medium text-2xl"><%= @payments.count %> payment methods</h3>
    <p class="text-gray-500">This are the available payment method when booking</p>
  <% end %>

  <%= link_to dashboard_receipts_path, class:"p-6 border shadow-xl rounded-xl block hover:shadow-lg transition ease-in duration-300 relative overflow-hidden" do %>
    <div class="h-1 w-full absolute top-0 left-0 right-0" style="background-color: #A3C1AD">
    </div>
    <h3 class="font-medium text-2xl"><%= @receipts.count %> receipt</h3>
    <p class="text-gray-500">View dashboard page for receipts</p>
  <% end %>

  <%= link_to dashboard_billings_path, class:"p-6 border shadow-xl rounded-xl block hover:shadow-lg transition ease-in duration-300 relative overflow-hidden" do %>
    <div class="h-1 w-full absolute top-0 left-0 right-0" style="background-color: #FFBF00">
    </div>
    <h3 class="font-medium text-2xl"><%= @billings.count %> billings information</h3>
    <p class="text-gray-500">List of user's billing information recorded</p>
  <% end %>

  <%= link_to dashboard_categories_path, class:"p-6 border shadow-xl rounded-xl block hover:shadow-lg transition ease-in duration-300 relative overflow-hidden" do %>
    <div class="h-1 w-full absolute top-0 left-0 right-0" style="background-color: #7CB9E8">
    </div>
    <h3 class="font-medium text-2xl"><%= @categories.count %> categories</h3>
    <p class="text-gray-500">List of categories</p>
  <% end %>
</div>

app/views/dashboard/payments.html.erb
<% provide(:title, "Dashboard-Payments")%>
<div class="flex items-center justify-between pb-6 border-b mb-6">
  <h1 class="text-5xl font-bold text-gray-700">Payment method's Dashboard</h1>
</div>

<table class="table-auto border-collapse border-slate-400 w-full">
  <thead class="bg-slate-50 dark:bg-slate-700">
    <tr>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">id</th>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Payment method</th>    
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <%= content_tag :tr, id: dom_id(payment), class: dom_class(payment) do %>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= payment.id %></td>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-sky-800 underline font-bold"><%= payment.name %></td>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/dashboard/services.html.erb
<% provide(:title, "Dashboard-Services")%>
<div class="flex items-center justify-between pb-6 border-b mb-6">
  <h1 class="text-5xl font-bold text-gray-700">Services's Dashboard</h1>
   <%= link_to "Add Service", new_service_path, class: button_class(theme: "primary")%>
</div>

<table class="table-auto border-collapse border-slate-400 w-full">
  <thead class="bg-slate-50 dark:bg-slate-700">
    <tr>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">id</th>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Name</th>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">description</th>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Image</th>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Price</th>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Available Date(s)</th>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Available</th>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Category</th>
      <th class="border border-slate-300 dark:border-slate-600 text-gray-100 font-semibold p-4">Action</th>         
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <%= content_tag :tr, id: dom_id(service), class: dom_class(service) do %>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= service.id %></td>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-sky-800 underline font-bold"><%= link_to service.name, service_path(service) %></td>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= service.description.to_plain_text %></td>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= image_tag service.image, class:"w-24" %></td>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800">₱<%= service.price %></td>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800">
          <% service.available_slots.each do |slot| %>
            <%= Time.strptime(slot['start_time'],"%H:%M").strftime("%I:%M %p") %> - <%= Time.strptime(slot['end_time'],"%H:%M").strftime("%I:%M %p") %><br><br>
          <% end %>
        </td>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800">
          <% service.available_slots.each do |slot| %>
            <%= slot['slots']%><br>
          <% end %>
        </td>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800"><%= service.category.name %></td>
        <td class="border border-slate-300 dark:border-slate-700 p-4 text-gray-800">
          <%= link_to "edit", edit_service_path(service), class: "bg-sky-500 hover:bg-sky-600 text-white rounded-md px-4 py-2 mt-2" if current_user.admin? %><br><br>
          <%= link_to "delete", @service, data: { turbo_method: :delete}, class: "bg-rose-500 hover:bg-rose-600 text-white rounded-md px-4 py-2 mt-2" if current_user.admin? %>
        </td>
      <% end %>
    <% end %>
  </tbody>
</table>