config/routes.rb
Rails.application.routes.draw do
  # routes only accessible to users
  resources :billings
  resources :bookings
  get "cart", to: "cart#show"
  post "cart/add"
  post "cart/remove"
  get 'cart/show'
  
  # routes only accessible to admin
  authenticated :user, ->(user) { user.admin? } do
    get "dashboard", to: "dashboard#index"
    get "dashboard/bookings"
    get "dashboard/users"
    get "dashboard/services"
    get "dashboard/billings"
    get "dashboard/payments"
    get "dashboard/categories"
    get "dashboard/receipts"
    resources :categories
    resources :services
    resources :payments
  end

  devise_for :users
  root "bookings#index"

  # errors route 
  match "/404", to: "errors#not_found", via: :all
  match "/505", to: "errors#internal_server_error", via: :all

  # graphql
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :billing

  validates :street, :barangay, :city, :zipcode, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  has_many :bookings
  
  has_one :address, dependent: :destroy, inverse_of: :billing
  accepts_nested_attributes_for :address
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :service
  belongs_to :payment
  belongs_to :billing
  has_many :receipts, dependent: :destroy

  validates :user, presence: true
  validates :service, presence: true
  validates :payment, presence: true

  enum status: { pending: 0, served: 1, cancelled: 2 }
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items
  has_many :services, through: :cart_items

  def total 
    cart_items.to_a.sum { |cart_item| cart_item.total }
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :service
  belongs_to :cart

  def total
    service.price * slot
  end
end

app/models/category.rb
class Category < ApplicationRecord
  include ValidationConcern
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :services

  default_scope -> { order(updated_at: :desc) }
end

app/models/payment.rb
class Payment < ApplicationRecord
  validates :name, presence: true
  
  has_many :bookings
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :user
  # belongs_to :billing
  belongs_to :booking
end

app/models/service.rb
class Service < ApplicationRecord
  include ValidationConcern
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :user
  belongs_to :category
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :bookings

  validates :price, presence: true
  validates :available_date, presence: true, comparison: { greater_than: Time.zone.now, message: "must be set in the future or later." }
  validates :available_slots, presence: true
  validates :category_id, presence: true
  
  default_scope -> { order(updated_at: :desc) }
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :service
end

app/models/user.rb
class User < ApplicationRecord
  include UserConcern

  has_many :services, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :billings, dependent: :destroy
  has_many :receipts, dependent: :destroy
  has_one :cart, dependent: :destroy
end

app/controllers/cart_controller.rb
require "pry"
class CartController < ApplicationController
  before_action :authenticate_user!

  def show
    @render_cart = false
  end

  def add
    @service = Service.find_by(id: params[:service_id])
    slot = params[:slot].to_i
    booked_time = params[:booked_time]
  
    current_item = @cart.cart_items.find_by(service_id: @service&.id)
    
    # binding.pry
    
    if current_item && slot > 0
      current_item.update(slot: slot, booked_time: booked_time, user_id: current_user.id)
    elsif slot <= 0
      current_item.destroy
    else
      @cart.cart_items.create(user_id: current_user.id, service_id: @service&.id, booked_time: booked_time, slot: slot)
    end
  
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Added to cart" }
    end
  end

  def remove
    CartItem.find_by(id: params[:id]).destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace("cart", partial: "cart/cart", locals: { cart: @cart })
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "Cinema Booking"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def flash_classes(flash_type)
    flash_base = 'px-2 py-4 mx-auto font-sans font-medium text-center text-white'
    {
      notice: "bg-teal-600 #{flash_base}",
      error: "bg-red-600 #{flash_base}",
      alert: "bg-red-600 #{flash_base}"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def nav_classes
    if ['devise/registrations', 'devise/sessions', 'devise/confirmations', 'devise/passwords',
        'devise/unlocks'].include?(params[:controller])
      'hidden'
    end
  end

  def label_class(options = {})
    "block mb-1 font-normal leading-normal #{options[:extended_classes]}"
  end

  def input_class(options = {})
    "rounded border border-gray-300 block w-full focus:outline-none focus:border-gray-400 outline-none focus-within:outline-none focus:ring-2 focus:ring-gray-200 #{options[:extended_classes]}"
  end

  def checkbox_class(options = {})
    "rounded border-gray-300 border focus:ring-2 focus:ring-gray-200 text-blue-500 mr-1 #{options[:extended_classes]}"
  end

  def link_class(options = {})
    "text-sky-700 underline hover:no-underline hover:text-gray-800 block #{options[:extended_classes]}"
  end

  def button_class(options = {})
    variant = options[:variant]
    theme = options[:theme]

    style_button(variant, theme_button(theme))
  end

  def theme_button(theme)
    themes = {
      primary: 'primary',
      secondary: 'secondary',
      transparent: 'transparent',
      dark: 'dark',

    }

    case theme
    when themes[:primary]
      'bg-sky-500 hover:bg-sky-600 text-white'
    when themes[:secondary]
      'bg-teal-600 hover:bg-teal-700 text-white'
    when themes[:transparent]
      'bg-transparent hover:bg-gray-100 text-gray-700'
    when themes[:dark]
      'bg-gray-800 text-white shadow-sm hover:bg-gray-900'
    else
      'bg-white border border-gray-300 shadow-sm hover:bg-gray-100'
    end
  end

  def style_button(variant, theme)
    base = 'rounded text-center font-sans font-normal outline-none leading-normal cursor-pointer transition ease-in-out duration-200 font-medium'

    case variant
    when 'large'
      "px-5 py-4 text-lg #{base} #{theme}"
    when 'small'
      "py-2 px-4 text-sm #{base} #{theme}"
    when 'expanded'
      "p-3 w-full block #{base} #{theme}"
    else
      "px-5 py-2 text-base #{base} #{theme}"
    end
  end
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/cart/_bookings.html.erb
<div class="grid grid-cols-1 md:grid-cols-3 gap-4">
  <% @cart.cart_items.each do |items| %>
    <% service = items.service %>
    <div class="rounded-md p-4 relative bg-gray-100">
      <h5 class="text-gray-800 text-2xl font-bold mb-2"><strong>Service Name: </strong><%= service.name %></h5>
      <p class="text-gray-700 mb-2"><strong>Description: </strong><%= service.description %></p>
      <p class="text-gray-700 mb-2"><strong>Price: </strong><%= service.price %></p>
      <p class="text-gray-700 mb-2"><strong>Booked Date: </strong><%= items.service.available_date.strftime("%B %e, %Y") %></p>
      <p class="text-gray-700 mb-2"><strong>Booked Time: </strong><%= items.booked_time.strftime("%I:%M %p") %></p>
      <p class="text-gray-700 mb-2"><strong>Booked Slot: </strong><%= items.slot %></p>
      <%= form_with(url: cart_add_path) do |form| %>
        <%= form.hidden_field :service_id, value: service.id %>
        <%= form.hidden_field :booked_time, value: items.booked_time %>
        <%= form.number_field :slot, value: items.slot, min: 1, class: input_class %>
        <br>
        <%= form.submit "Update cart", class: "bg-sky-500 hover:bg-sky-600 text-white rounded-md px-4 py-2 mt-2" %>
      <% end %>
      <%= form_with(url: cart_remove_path) do |form| %>
        <%= form.hidden_field :id, value: items.id %>
        <%= button_tag type: 'submit', class: 'absolute top-0 right-0 mt-2 mr-2 text-gray-600 hover:text-red-600' do %>
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
          </svg>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/cart/_cart.html.erb
<%= turbo_frame_tag "cart" do %>
<div class="flex items-center justify-between pb-6 border-b mb-6">
  <h1 class="text-5xl font-bold text-gray-700">Cart</h1>
  <% if @cart.cart_items.any? %>
    <h2 class="text-2xl font-bold text-sky-600">Total: <%= @cart.total %> </h2>
  <% end %>
</div>
  <% if @cart.cart_items.count > 0 %>
    <%= render "cart/bookings" %>
  <% else %>
    <p>Your cart is empty.</p>
  <% end %>
<% end %>

app/views/cart/show.html.erb
<% provide(:title, "#{current_user.name}'s Cart")%>
<div class="flex items-center justify-between pb-6 border-b mb-6">
<h1 class="text-5xl font-bold text-gray-700">Cart</h1>
</div>
<div class="container mx-auto px-4 py-8">

  <div class="flex flex-wrap -mx-4">
    <div class="w-full md:w-1/2 lg:w-2/3 px-4">
      <div class="bg-white rounded-lg shadow-md p-8">
        <h2 class="text-lg font-semibold mb-6">Cart Item(s)</h2>

        <ul class="divide-y divide-gray-300">
          <!-- Loop through cart items and display them -->
          <% @cart.cart_items.each do |items| %>
          <% service = items.service %>
          <li class="flex items-center py-4">
            <%= image_tag service.image, class: "w-16 h-16 object-cover rounded-md"%>
            <div class="ml-4">
              <h3 class="text-lg font-semibold"><%= service.name %></h3>
              <p class="text-gray-600"><%= service.price %></p>
              <p class="text-gray-600">Slots: <%= items.slot %></p>
            </div>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="w-full md:w-1/2 lg:w-1/3 px-4">
      <div class="bg-white rounded-lg shadow-md p-8">
        <h2 class="text-lg font-semibold mb-6">Order Summary</h2>
        <p class="text-gray-600">Total: <%= @cart.total %></p>
        <%= link_to new_booking_path(cart: @cart)  do %>
          <button class="mt-6 w-full bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded">
            Proceed to Checkout
          </button>
        <% end %>
      </div>
    </div>
  </div>
</div>