config/routes.rb
Rails.application.routes.draw do
  # routes only accessible to users
  resources :billings
  resources :bookings
  get "cart", to: "cart#show"
  post "cart/add"
  post "cart/remove"
  get 'cart/show'
  
  # routes only accessible to admin
  authenticated :user, ->(user) { user.admin? } do
    get "dashboard", to: "dashboard#index"
    get "dashboard/bookings"
    get "dashboard/users"
    get "dashboard/services"
    get "dashboard/billings"
    get "dashboard/payments"
    get "dashboard/categories"
    get "dashboard/receipts"
    resources :categories
    resources :services
    resources :payments
  end

  devise_for :users
  root "bookings#index"

  # errors route 
  match "/404", to: "errors#not_found", via: :all
  match "/505", to: "errors#internal_server_error", via: :all

  # graphql
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :billing

  validates :street, :barangay, :city, :zipcode, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  has_many :bookings
  
  has_one :address, dependent: :destroy, inverse_of: :billing
  accepts_nested_attributes_for :address
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :service
  belongs_to :payment
  belongs_to :billing
  has_many :receipts, dependent: :destroy

  validates :user, presence: true
  validates :service, presence: true
  validates :payment, presence: true

  enum status: { pending: 0, served: 1, cancelled: 2 }
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items
  has_many :services, through: :cart_items

  def total 
    cart_items.to_a.sum { |cart_item| cart_item.total }
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :service
  belongs_to :cart

  def total
    service.price * slot
  end
end

app/models/category.rb
class Category < ApplicationRecord
  include ValidationConcern
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :services

  default_scope -> { order(updated_at: :desc) }
end

app/models/payment.rb
class Payment < ApplicationRecord
  validates :name, presence: true
  
  has_many :bookings
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :user
  # belongs_to :billing
  belongs_to :booking
end

app/models/service.rb
class Service < ApplicationRecord
  include ValidationConcern
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :user
  belongs_to :category
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :bookings

  validates :price, presence: true
  validates :available_date, presence: true, comparison: { greater_than: Time.zone.now, message: "must be set in the future or later." }
  validates :available_slots, presence: true
  validates :category_id, presence: true
  
  default_scope -> { order(updated_at: :desc) }
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :service
end

app/models/user.rb
class User < ApplicationRecord
  include UserConcern

  has_many :services, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :billings, dependent: :destroy
  has_many :receipts, dependent: :destroy
  has_one :cart, dependent: :destroy
end

app/controllers/billings_controller.rb
require "pry"
class BillingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_billing, only: %i(show edit update destroy)

  def index
    @billings = Billing.all
  end

  def show; end
  
  def new
    @billing = current_user.billings.build
    @billing.build_address
  end

  def edit; end

  def create
    @billing = current_user.billings.build(billing_params)
    @billing.complete_address = @billing.address.attributes.values_at(*%w[street barangay city, zipcode]).join(', ')

    respond_to do |format|
      if @billing.save
        format.html { redirect_to cart_url, notice: "Billing was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    @billing = current_user.billings.build(billing_params)
    @billing.complete_address = @billing.address.attributes.values_at(*%w[street barangay city, zipcode]).join(', ')
    respond_to do |format|
      if @billing.update(billing_params)
        format.html { redirect_to billing_url(@billing), notice: "Billing was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @billing.destroy

    respond_to do |format|
      format.html { redirect_to billings_url, notice: "Billing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_billing
      @billing = Billing.find(params[:id])
    end

    def billing_params
      params.require(:billing).permit(:user_id, :complete_address, address_attributes: %i(street barangay city province zipcode user_id))
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "Cinema Booking"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def flash_classes(flash_type)
    flash_base = 'px-2 py-4 mx-auto font-sans font-medium text-center text-white'
    {
      notice: "bg-teal-600 #{flash_base}",
      error: "bg-red-600 #{flash_base}",
      alert: "bg-red-600 #{flash_base}"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def nav_classes
    if ['devise/registrations', 'devise/sessions', 'devise/confirmations', 'devise/passwords',
        'devise/unlocks'].include?(params[:controller])
      'hidden'
    end
  end

  def label_class(options = {})
    "block mb-1 font-normal leading-normal #{options[:extended_classes]}"
  end

  def input_class(options = {})
    "rounded border border-gray-300 block w-full focus:outline-none focus:border-gray-400 outline-none focus-within:outline-none focus:ring-2 focus:ring-gray-200 #{options[:extended_classes]}"
  end

  def checkbox_class(options = {})
    "rounded border-gray-300 border focus:ring-2 focus:ring-gray-200 text-blue-500 mr-1 #{options[:extended_classes]}"
  end

  def link_class(options = {})
    "text-sky-700 underline hover:no-underline hover:text-gray-800 block #{options[:extended_classes]}"
  end

  def button_class(options = {})
    variant = options[:variant]
    theme = options[:theme]

    style_button(variant, theme_button(theme))
  end

  def theme_button(theme)
    themes = {
      primary: 'primary',
      secondary: 'secondary',
      transparent: 'transparent',
      dark: 'dark',

    }

    case theme
    when themes[:primary]
      'bg-sky-500 hover:bg-sky-600 text-white'
    when themes[:secondary]
      'bg-teal-600 hover:bg-teal-700 text-white'
    when themes[:transparent]
      'bg-transparent hover:bg-gray-100 text-gray-700'
    when themes[:dark]
      'bg-gray-800 text-white shadow-sm hover:bg-gray-900'
    else
      'bg-white border border-gray-300 shadow-sm hover:bg-gray-100'
    end
  end

  def style_button(variant, theme)
    base = 'rounded text-center font-sans font-normal outline-none leading-normal cursor-pointer transition ease-in-out duration-200 font-medium'

    case variant
    when 'large'
      "px-5 py-4 text-lg #{base} #{theme}"
    when 'small'
      "py-2 px-4 text-sm #{base} #{theme}"
    when 'expanded'
      "p-3 w-full block #{base} #{theme}"
    else
      "px-5 py-2 text-base #{base} #{theme}"
    end
  end
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/billings/_billing.html.erb
<div id="<%= dom_id billing %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= billing.complete_address %>
    <%= billing.user.name %>
    <%= billing.user.email %>
    <%= billing.user.mobile %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= billing.address.street %>
    <%= billing.address.city %>
    <%= billing.address.barangay %>
    <%= billing.address.zipcode %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this billing", billing, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this billing', edit_billing_path(billing), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/billings/_form.html.erb
<%= form_with(model: billing, class: "contents") do |form| %>
  <%= render "shared/error_messages", object: form.object %>

  <%= form.fields_for :address do |address_form| %>
    <div class="mb-6">
        <%= address_form.label :street, class: label_class %>
        <%= address_form.text_field :street, class: input_class %>
      </div>
      <div class="mb-6">
        <%= address_form.label :barangay, class: label_class %>
        <%= address_form.text_field :barangay, class: input_class %>
      </div>

      <div class="mb-6">
        <%= address_form.label :city, class: label_class %>
        <%= address_form.text_field :city, class: input_class %>
      </div>

      <div class="mb-6">
        <%= address_form.label :province, class: label_class %>
        <%= address_form.text_field :province, class: input_class %>
      </div>

      <div class="mb-6">
        <%= address_form.label :zipcode, class: label_class %>
        <%= address_form.text_field :zipcode, class: input_class %>
      </div>

      <%= address_form.hidden_field :user_id, value: current_user.id %>
  <% end %>

  <div class="mb-6">
    <%= form.submit class:"w-full text-white bg-sky-600 hover:bg-sky-700 focus:ring-4 focus:outline-none focus:ring-sky-300 font-medium rounded text-sm w-1/4 px-5 py-2.5 text-center"%>
  </div>
  
<% end %>

app/views/billings/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing billing</h1>

  <%= render "form", billing: @billing %>

  <%= link_to "Show this billing", @billing, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to billings", billings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/billings/index.html.erb
<% provide(:title, "Billing")%>
<div class="flex items-center justify-between pb-6 border-b mb-6">
  <h1 class="text-5xl font-bold text-gray-700">Billing information</h1>
  <%= link_to 'New billing', new_billing_path, class: button_class(theme: "primary", variant: "large") %>
</div>

  <div id="billings" class="min-w-full">
    <%= render @billings %>
  </div>
</div>

app/views/billings/new.html.erb
<% provide(:title, "Billing")%>
<div class="flex items-center justify-between pb-6 border-b mb-6">
  <h1 class="text-5xl font-bold text-gray-700"><%= @billing.user.first_name.capitalize %>'s billing information</h1>
</div>
  <%= render "form", billing: @billing %>

  <%= link_to 'Back to billings', billings_path, class: button_class(theme: "dark", variant: "expanded")%>
</div>

app/views/billings/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @billing %>

    <%= link_to 'Edit this billing', edit_billing_path(@billing), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this billing', billing_path(@billing), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to billings', billings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>