config/routes.rb
Rails.application.routes.draw do
  # routes only accessible to users
  resources :billings
  resources :bookings
  get "cart", to: "cart#show"
  post "cart/add"
  post "cart/remove"
  get 'cart/show'
  
  # routes only accessible to admin
  authenticated :user, ->(user) { user.admin? } do
    get "dashboard", to: "dashboard#index"
    get "dashboard/bookings"
    get "dashboard/users"
    get "dashboard/services"
    get "dashboard/billings"
    get "dashboard/payments"
    get "dashboard/categories"
    get "dashboard/receipts"
    resources :categories
    resources :services
    resources :payments
  end

  devise_for :users
  root "bookings#index"

  # errors route 
  match "/404", to: "errors#not_found", via: :all
  match "/505", to: "errors#internal_server_error", via: :all

  # graphql
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :billing

  validates :street, :barangay, :city, :zipcode, presence: true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  has_many :bookings
  
  has_one :address, dependent: :destroy, inverse_of: :billing
  accepts_nested_attributes_for :address
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :service
  belongs_to :payment
  belongs_to :billing
  has_many :receipts, dependent: :destroy

  validates :user, presence: true
  validates :service, presence: true
  validates :payment, presence: true

  enum status: { pending: 0, served: 1, cancelled: 2 }
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items
  has_many :services, through: :cart_items

  def total 
    cart_items.to_a.sum { |cart_item| cart_item.total }
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :service
  belongs_to :cart

  def total
    service.price * slot
  end
end

app/models/category.rb
class Category < ApplicationRecord
  include ValidationConcern
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :services

  default_scope -> { order(updated_at: :desc) }
end

app/models/payment.rb
class Payment < ApplicationRecord
  validates :name, presence: true
  
  has_many :bookings
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :user
  # belongs_to :billing
  belongs_to :booking
end

app/models/service.rb
class Service < ApplicationRecord
  include ValidationConcern
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  belongs_to :user
  belongs_to :category
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_many :bookings

  validates :price, presence: true
  validates :available_date, presence: true, comparison: { greater_than: Time.zone.now, message: "must be set in the future or later." }
  validates :available_slots, presence: true
  validates :category_id, presence: true
  
  default_scope -> { order(updated_at: :desc) }
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :service
end

app/models/user.rb
class User < ApplicationRecord
  include UserConcern

  has_many :services, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :billings, dependent: :destroy
  has_many :receipts, dependent: :destroy
  has_one :cart, dependent: :destroy
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_navbar.html.erb
<nav class="flex flex-wrap items-center justify-between py-3 text-gray-700 bg-white container mx-auto px-4">
  <div class="block lg:hidden">
    <%# Mobile nav toggle %>
    <button class="flex items-center p-2 -mr-1 rounded-lg focus:bg-gray-100">
      <svg class="stroke-current text-gray-500 w-7 h-7" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>Menu</title><g fill="none"><path d="M4 6h16M4 12h8m-8 6h16" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></g></svg>
    </button>
  </div>
  <div class="items-center w-full text-center lg:flex-1 lg:flex lg:text-left pt-2 lg:pt-0 hidden" data-nav-target="menu">
    <div class="lg:flex-grow">
      <%= link_to "Home", root_path, class: "p-3 hover:bg-gray-100 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
      <%= link_to "Services", services_path, class: "p-3 hover:bg-gray-100 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" if user_signed_in? && current_user.admin? %>
    </div>
    <div class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">
      <div><%# More links can go here %></div>
      <% if user_signed_in? %>
      <%= link_to "Categories", categories_path, class: "p-3 hover:bg-gray-100 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" if current_user.admin? %>

      <% if @cart.cart_items.any? %>
        <%= link_to cart_path, class: "relative inline-flex items-center p-3 text-sm font-medium text-center text-white rounded-lg bg-sky-500 hover:bg-sky-700" do %>
        <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" d="M2.25 3h1.386c.51 0 .955.343 1.087.835l.383 1.437M7.5 14.25a3 3 0 00-3 3h15.75m-12.75-3h11.218c1.121-2.3 2.1-4.684 2.924-7.138a60.114 60.114 0 00-16.536-1.84M7.5 14.25L5.106 5.272M6 20.25a.75.75 0 11-1.5 0 .75.75 0 011.5 0zm12.75 0a.75.75 0 11-1.5 0 .75.75 0 011.5 0z" /></svg>
        <span class="sr-only">Notifications</span>
        <div class="absolute inline-flex items-center justify-center w-6 h-6 text-xs font-bold text-white bg-red-500 border-2 border-white rounded-full -top-2 -right-2 dark:border-gray-900"><%= @cart.cart_items.count%></div>
      <% end %>
      <% end %>
      <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "p-3 hover:bg-gray-100 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>

      <%= link_to "Dashboard", dashboard_path, class: "text-white bg-sky-700 hover:bg-sky-800 focus:ring-2 focus:outline-none focus:ring-sky-300 font-medium rounded-md text-sm px-4 py-2.5 text-center inline-flex items-center dark:bg-sky-600 dark:hover:bg-sky-700 dark:focus:ring-sky-800" if current_user.admin? %>

      <% else %>
        <%= link_to "Sign in", new_user_session_path, class:"p-3 hover:bg-gray-100 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
        <%= link_to "Sign up", new_user_registration_path, class:"p-3 hover:bg-gray-100 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block lg:ml-2" %>

        <span class="h-5 w-px bg-gray-200 mx-3"></span>

        

        <%= link_to "https://github.com/ninjadanray/service-booking", target: :_blank, class: "group lg:ml-2 flex justify-center" do %>
          <svg class="fill-current text-gray-400 group-hover:text-sky-600" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "actiontext", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header>
      <%= render "layouts/navbar" %>
      <%= render "shared/notifications" %>
    </header>
    <main class="container mx-auto mt-12 px-5 mb-12">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50">
    <svg aria-hidden="true" class="flex-shrink-0   inline w-5 h-5 mr-3" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
    <span class="sr-only">Danger</span>
    <div>
      <span class="font-medium"><%= pluralize(object.errors.count, "error") %> prohibited this object from being saved:</span>
      <ul class="mt-1.5 ml-4 list-disc list-inside">
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_notifications.html.erb
<div class="container mx-auto">
  <% if alert %>
    <div class="flex p-4 mb-4 text-sm text-red-800 border border-red-300 rounded-lg bg-red-50" role="alert">
      <span class="font-medium"><%= alert %></span>
    </div>
  <% end %>

  <% if notice %>
    <div class="flex p-4 mb-4 text-sm text-sky-800 border border-sky-300 rounded-lg bg-sky-50" role="alert">
      <span class="font-medium"><%= notice %></span>
    </div>
  <% end %>
</div>